### ISSUE TITLE
Laravel9 PHP8 无法上传图片

### ISSUE THREAD

**Issue by mofashi998** [zgldh/qiniu-laravel-storage#86]
Laravel9 PHP8 无法上传图片
`TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in file D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\qiniu\php-sdk\src\Qiniu\Auth.php on line 117
`
`
#0 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\qiniu\php-sdk\src\Qiniu\Auth.php(117): count(NULL)
#1 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\qiniu\php-sdk\src\Qiniu\Auth.php(227): Qiniu\Auth-&gt;signQiniuAuthorization(&#039;http://rs.qiniu...&#039;, &#039;GET&#039;, NULL, Object(Qiniu\Http\Header))
#2 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\qiniu\php-sdk\src\Qiniu\Storage\BucketManager.php(959): Qiniu\Auth-&gt;authorizationV2(&#039;http://rs.qiniu...&#039;, &#039;GET&#039;, NULL, &#039;application/x-w...&#039;)
#3 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\qiniu\php-sdk\src\Qiniu\Storage\BucketManager.php(954): Qiniu\Storage\BucketManager-&gt;getV2(&#039;http://rs.qiniu...&#039;)
#4 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\qiniu\php-sdk\src\Qiniu\Storage\BucketManager.php(578): Qiniu\Storage\BucketManager-&gt;rsGet(&#039;/stat/ZGRzdWppZ...&#039;)
#5 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\zgldh\qiniu-laravel-storage\src\QiniuAdapter.php(263): Qiniu\Storage\BucketManager-&gt;stat(&#039;ddsujie&#039;, &#039;images/3ad8320c...&#039;)
#6 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\zgldh\qiniu-laravel-storage\src\QiniuAdapter.php(708): zgldh\QiniuStorage\QiniuAdapter-&gt;getMetadata(&#039;images/3ad8320c...&#039;)
#7 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\league\flysystem\src\Filesystem.php(48): zgldh\QiniuStorage\QiniuAdapter-&gt;fileExists(&#039;images/3ad8320c...&#039;)
#8 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(159): League\Flysystem\Filesystem-&gt;has(&#039;images/3ad8320c...&#039;)
#9 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Form\Field\UploadField.php(101): Illuminate\Filesystem\FilesystemAdapter-&gt;exists(&#039;images/3ad8320c...&#039;)
#10 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Form\Field\UploadField.php(197): Dcat\Admin\Form\Field\File-&gt;renameIfExists(Object(Illuminate\Http\UploadedFile))
#11 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Form\Concerns\HasFiles.php(50): Dcat\Admin\Form\Field\File-&gt;upload(Object(Illuminate\Http\UploadedFile))
#12 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Form.php(685): Dcat\Admin\Form-&gt;handleUploadFile(Array)
#13 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Form.php(621): Dcat\Admin\Form-&gt;beforeStore(Array)
#14 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Controllers\AdminController.php(146): Dcat\Admin\Form-&gt;store()
#15 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Controller.php(54): Dcat\Admin\Http\Controllers\AdminController-&gt;store()
#16 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(45): Illuminate\Routing\Controller-&gt;callAction(&#039;store&#039;, Array)
#17 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Route.php(261): Illuminate\Routing\ControllerDispatcher-&gt;dispatch(Object(Illuminate\Routing\Route), Object(App\Admin\Controllers\AppServiceController), &#039;store&#039;)
#18 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Route.php(204): Illuminate\Routing\Route-&gt;runController()
#19 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Router.php(725): Illuminate\Routing\Route-&gt;run()
#20 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Routing\Router-&gt;Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#21 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\WebUploader.php(31): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\WebUploader-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#23 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\Session.php(12): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#24 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\Session-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#25 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\Permission.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\Permission-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#27 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\Bootstrap.php(19): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\Bootstrap-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#29 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\Pjax.php(22): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#30 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\Pjax-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#31 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\Authenticate.php(26): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\Authenticate-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#33 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Middleware\SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#35 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#37 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\View\Middleware\ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#38 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#39 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(121): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Session\Middleware\StartSession.php(64): Illuminate\Session\Middleware\StartSession-&gt;handleStatefulRequest(Object(Illuminate\Http\Request), Object(Illuminate\Session\Store), Object(Closure))
#41 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Session\Middleware\StartSession-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#42 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#44 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Cookie\Middleware\EncryptCookies.php(67): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#45 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#46 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\dcat\laravel-admin\src\Http\Middleware\Application.php(15): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#47 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Dcat\Admin\Http\Middleware\Application-&gt;handle(Object(Illuminate\Http\Request), Object(Closure), &#039;admin&#039;)
#48 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Router.php(727): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#50 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Router.php(702): Illuminate\Routing\Router-&gt;runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#51 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Router.php(666): Illuminate\Routing\Router-&gt;runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#52 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Routing\Router.php(655): Illuminate\Routing\Router-&gt;dispatchToRoute(Object(Illuminate\Http\Request))
#53 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(167): Illuminate\Routing\Router-&gt;dispatch(Object(Illuminate\Http\Request))
#54 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(141): Illuminate\Foundation\Http\Kernel-&gt;Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#55 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#56 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull.php(31): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#57 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#58 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#59 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TrimStrings.php(40): Illuminate\Foundation\Http\Middleware\TransformsRequest-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#60 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#61 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#63 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance.php(86): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#64 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#65 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Http\Middleware\HandleCors.php(49): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#66 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\HandleCors-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#67 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Http\Middleware\TrustProxies.php(39): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies-&gt;handle(Object(Illuminate\Http\Request), Object(Closure))
#69 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(116): Illuminate\Pipeline\Pipeline-&gt;Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#70 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(142): Illuminate\Pipeline\Pipeline-&gt;then(Object(Closure))
#71 D:\phpstudy_pro\WWW\laravel9.dd.com\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(111): Illuminate\Foundation\Http\Kernel-&gt;sendRequestThroughRouter(Object(Illuminate\Http\Request))
#72 D:\phpstudy_pro\WWW\laravel9.dd.com\public\index.php(52): Illuminate\Foundation\Http\Kernel-&gt;handle(Object(Illuminate\Http\Request))
#73 {main}
`

**Comment by mofashi998** [comment]
我暂时的解决方法 is_countable($body) 新增这一句

`
        // append body
        $data .= "\n\n";
        if (
            is_countable($body)
            && count($body) > 0
            && isset($headers["Content-Type"])
            && $headers["Content-Type"] != "application/octet-stream"
        ) {
            $data .= $body;
        }
`
